language: node_js
node_js:
  - "6"
services:
  - mysql
env:
- TRAVIS=true
before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot  
script: npm test
after_success: 'npm run coveralls'